// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpjPnfopVWWXdPtRIbivAywr0SiLHmd7w',
    appId: '1:1038993325004:web:d0b01ed162813e3a10fb69',
    messagingSenderId: '1038993325004',
    projectId: 'tenants-e1186',
    authDomain: 'tenants-e1186.firebaseapp.com',
    storageBucket: 'tenants-e1186.appspot.com',
    measurementId: 'G-ZJ51KMNEJM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBFYER_BsWxpJZ8GJG2PDDlsLZH4K0KRU',
    appId: '1:1038993325004:android:1f418ad3b519eccc10fb69',
    messagingSenderId: '1038993325004',
    projectId: 'tenants-e1186',
    storageBucket: 'tenants-e1186.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCy2aA-pdlxLkBbExsJsbTEclmLRnKexGo',
    appId: '1:1038993325004:ios:b51824391daf898510fb69',
    messagingSenderId: '1038993325004',
    projectId: 'tenants-e1186',
    storageBucket: 'tenants-e1186.appspot.com',
    iosBundleId: 'com.example.tenantsApp',
  );
}
